server:
  port: 8062
  base_url: "http://static.sineshop.xin"

database:
  host: "127.0.0.1"
  port: 3306
  user: "sine"
  password: "DkPBNrGyKZnx65ty"
  dbname: "sine"
  charset: "utf8mb4"

jwt:
  secret: "the_moye_yyds"
  expire_hours: 168

storage:
  base_url: "/sine/data/" # 别问，问就是我怕哪里还用到了base_url就没删
  base_path: "/sine/data/"
  icon_path: "images/app_icon"
  preview_path: "images/app_previews"
  banner_path: "images/banana"
  popup_path: "images/popup"
  apk_path: "apks"

user:
  default_avatar_url: "http://smart.huanjin.xin/images/user_avatar/default_avatar.png"

file_server:
  api_url: "http://110.42.57.123:800"

smtp:
  host: "smtp.qiye.aliyun.com"
  port: 465
  user: "postmaster@sineshop.xin"
  password: "Sine114514"
  sender_email: "postmaster@sineshop.xin"
  sender_name: "弦-应用商店"

# 废弃
app_download_api: ""
